import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {harness,refresh,owner,reviewer,publicReviewer} from '../test/helpers.js';
import {createManifest,submit,prepare} from '../src/emitter.js';
import {asset} from '../src/paths.js';
import {reviewerAdapters} from '../src/adapters.js';
const h=await harness(true);
try{
  const steps:{step:string;status:string}[]=[];
  const check=(step:string,condition:boolean)=>{assert(condition,step);steps.push({step,status:'PASS'});};
  const m=createManifest(h.next());m.emittedAt=h.next().emittedAt;
  check('PRIME emitter creates versioned structured manifest',m.schemaVersion==='1.0' && m.synthetic);
  const request=prepare(m,h.secret);
  check('Manifest validates and HMAC signer produces signature metadata',request.headers['x-evidence-signature']!.length===64);
  const accepted=await fetch(`${h.url}/v1/ingest`,{method:'POST',...request});check('PRIME creates, validates, signs and submits structured manifest',accepted.status===202);
  check('Replay rejected',(await fetch(`${h.url}/v1/ingest`,{method:'POST',...request})).status===409);
  check('First publication held and normalized',(await h.store.candidates())[0]!.normalized.version==='1' && (await h.bus.projection(reviewer)).length===0);
  await h.bus.review(owner,m.eventId,'approve','Synthetic baseline owner approval.');
  check('Owner approval publishes baseline candidate',(await h.store.current('prime'))?.eventId===m.eventId);
  const update=refresh(m,h.next().emittedAt);update.tests!.passed+=5;
  check('Same-maturity evidence refresh automatically published',(await submit(update,`${h.url}/v1/ingest`,h.secret)).status==='auto_refreshed');
  const promotion=refresh(update,h.next().emittedAt);promotion.maturity='DEPLOYED';
  check('Maturity promotion held for owner review',(await submit(promotion,`${h.url}/v1/ingest`,h.secret)).status==='needs_review');
  check('Candidate hidden from reviewer',(await h.bus.projection(reviewer))[0]!.eventId===update.eventId);
  await h.bus.review(owner,promotion.eventId,'approve','Synthetic owner-reviewed maturity change, not a real deployment.');
  check('Approved reviewer update exposed',(await h.bus.projection(reviewer))[0]!.eventId===promotion.eventId);
  await h.publish('rig','restricted');
  check('Lower-tier reviewer cannot see higher-tier evidence',(await h.bus.projection(publicReviewer)).length===0 && (await h.bus.projection(reviewer)).length===1);
  const adapters=reviewerAdapters(h.bus,reviewer);
  const context=await adapters.copilotContext('prime');
  check('Deep Dive and Copilot receive only approved tier-visible data',context.current[0]!.eventId===promotion.eventId && context.changes.every(c=>c.system==='prime'));
  const reconciliation=await h.bus.reconcile(owner,[{source:'prime',latestEventId:randomUUID(),observedAt:new Date(h.now()).toISOString(),schemaVersion:'1.0',evidencePresent:true,conflicting:false}]);
  check('Reconciliation detects missed/stale source',reconciliation[0]!.status==='stale');
  const bad=refresh(promotion,h.next().emittedAt);check('Failed signed ingest retains previous approved state',(await h.send(bad,{'x-evidence-signature':'0'.repeat(64)})).status===401 && (await h.store.current('prime'))!.eventId===promotion.eventId);
  const proof={schemaVersion:'1',synthetic:true,generatedAt:new Date().toISOString(),storage:'Postgres',server:'compiled production modules',steps,reviewerProjection:await adapters.current(),copilotContext:await adapters.copilotContext(),reconciliation};
  await mkdir(asset('reports'),{recursive:true});await writeFile(asset('reports/demo-proof.json'),JSON.stringify(proof,null,2)+'\n');
  process.stdout.write(JSON.stringify({status:'PASS',steps:steps.length,proof:'reports/demo-proof.json'})+'\n');
}finally{await h.close();}
